FROM node:22-alpine as builder

RUN npm install -g pnpm

WORKDIR /app

COPY pnpm-lock.yaml ./ 
COPY package.json ./ 

RUN pnpm install

COPY . .

RUN pnpm build

FROM nginx:alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/.next /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
