services:
  db:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nextjs:
    container_name: nextjs_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://fastapi:8080
    ports:
      - "3000:3000"
    networks:
      - app-network

  fastapi:
    container_name: fastapi_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app
    command: sh -c "alembic upgrade head && fastapi run src/presentation/main.py  --port 8080"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
