version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@db/mydatabase
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    command: fastapi run src/presentation/main.py --port 8080
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge