site_name: Teste Globo
repo_url: https://github.com/deivisonisidoro/test_globo


theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo claro

nav:
  - Home: index.md
  - Arquitetura do Projeto: architecture.md
  - ...

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - https://cdn.jsdelivr.net/npm/mermaid@8.8.4/dist/mermaid.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@8.8.4/dist/mermaid.min.js
watch:
  - src
  - tests

plugins:
  - search:
      lang: pt
  - awesome-pages
  - mkdocstrings:
      handlers:
        python:
          paths: [apps]
